# Generated by Django 4.0.4 on 2022-05-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('course_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=500)),
                ('correct_answers', models.CharField(max_length=1000)),
                ('for_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.courses')),
                ('for_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='uploads/')),
                ('world_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=1000)),
                ('for_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.tests')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='MessagesSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='MessagesReciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('members', models.ManyToManyField(to='my_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_from_reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.messagesreciever')),
                ('content_from_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.messagessender')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.users')),
            ],
        ),
    ]
