# Generated by Django 4.0.4 on 2022-09-30 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='uploads/')),
                ('world_points', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(to='my_app.customusers'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.customusers'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(to='my_app.customusers'),
        ),
        migrations.AlterField(
            model_name='messagesreciever',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.customusers'),
        ),
        migrations.AlterField(
            model_name='messagessender',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.customusers'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.customusers'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
