# Generated by Django 4.0.4 on 2022-09-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_customusers_courses_students_alter_chat_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='profile_pic',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
