# Generated by Django 4.0.4 on 2022-09-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_customusers_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
