# Generated by Django 4.0.4 on 2022-09-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_customusers_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ForeignKey(default=2020, on_delete=django.db.models.deletion.CASCADE, to='my_app.customusers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(null=True, to='my_app.customusers'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='world_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='messagesreciever',
            name='reciever',
            field=models.ForeignKey(default=2020, on_delete=django.db.models.deletion.CASCADE, to='my_app.customusers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagessender',
            name='sender',
            field=models.ForeignKey(default=2020, on_delete=django.db.models.deletion.CASCADE, to='my_app.customusers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='user',
            field=models.ForeignKey(default=2020, on_delete=django.db.models.deletion.CASCADE, to='my_app.customusers'),
            preserve_default=False,
        ),
    ]
