# Generated by Django 4.0.4 on 2022-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_chat_users_alter_courses_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='cover_photos'),
        ),
    ]
