# Generated by Django 4.0.4 on 2022-09-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
